<!-- 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
 -->
<?php $startTime = microtime(true);

function numDivisors($int)
{
	$divCount = 0;
	$sqrt = sqrt($int);
	for ($i=1; $i <= $sqrt; $i++) { 
		if ($i==$sqrt) {
			$divCount++;
		}
		else if ($int%$i==0) {
			$divCount+=2;
		}
	}
	return $divCount;
}
$total = 0;
$add = 1;
while ($total >= 0) {
	$total += $add;
	if (numDivisors($total)>500) {
		$numberOfDivPlus500 = $total;
		break;
	}
	$add++;
}

$answer = $numberOfDivPlus500;
$endTime = microtime(true);
echo "Answer: ",$answer,"\nTime: ",($endTime - $startTime),"\n";
// Answer: 76576500
// Time:3.834s