<!-- 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 -->
<?php $startTime = microtime(true);

$upTo = 100;

for ($n=1; $n <= $upTo; $n++) {
	$pent[$n] = ($n*((3*$n)-1))/2;
}

for ($i=1; $i <= $upTo; $i++) { 
	for ($j=$i+1; $j <= $upTo; $j++) {
		if ($pent[$i]>$pent[$j]) {
		 	$difference = $pent[$i]-$pent[$j];
		}
		else
		{
			$difference = $pent[$j]-$pent[$i];
		}
		if (in_array(($pent[$i]+$pent[$j]),$pent) && in_array($difference,$pent)) {
			echo $pent[$i]," + ",$pent[$j]," = ",($pent[$i]+$pent[$j]),"\n";

		}
	}
}
// && in_array($pent,$pent[$i]+$pent[$j]))



$answer = 0;
$endTime = microtime(true);
echo "Answer: ",$answer,"\nTime: ",($endTime - $startTime),"\n";
// Answer: 
// Time: 
