<!-- 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 -->
<?php $startTime = microtime(true);

$upTo = 2200;//added hundreds until result and break
$D = 0;
function isPentagonal($input){
	$number = (sqrt((24*$input)+1)+1)/6;
	if (floor($number) == $number)
	{
		return true;
	}
	return false;
}
for ($i=1; $i <= $upTo; $i++) { 
	for ($j=$i+1; $j <= $upTo; $j++) {
		$pentI = ($i*((3*$i)-1))/2;
		$pentJ = ($j*((3*$j)-1))/2;
		if ($pentI>$pentJ) {
		 	$difference = $pentI-$pentJ;
		}
		else
		{
			$difference = $pentJ-$pentI;
		}
		if (is_Pentagonal($pentI+$pentJ) && is_Pentagonal($difference)) {
			$D = $difference;
			break 2;
		}
	}
}

$answer = $D;
$endTime = microtime(true);
echo "Answer: ",$answer,"\nTime: ",($endTime - $startTime),"\n";
// Answer: 5482660
// Time: 1.49s
