<!-- 
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	P4,n=n2	 	1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
-->
<?php $startTime = microtime(true);

function getPolygon($numOfSides,$inputNum){
	return (($inputNum*$inputNum*($numOfSides-2))-($inputNum*($numOfSides-4)))/2;
}
function isPolygon($numOfSides,$inputNum){
	$number = (sqrt((((8*$numOfSides)-16)*$inputNum)+(($numOfSides-4)*($numOfSides-4)))+$numOfSides-4)/((2*$numOfSides)-4);
	if (floor($number) == $number)
	{
		return true;
	}
	return false;
}
function isMultiplePolygon($inputNum) {
	for ($i=3; $i <= 8; $i++) { 
		if (isPolygon($i,$inputNum)) {
			return true;
		}
	}
	return false;
}
function isOneOfEachPolygon($inputArray) {

	// for ($i=3; $i <= 8; $i++) { 
	// 	if (isPolygon($i,$inputNum)) {
	// 		return true;
	// 	}
	// }
	// return false;
}






for ($a=11; $a <= 99; $a++) {
	for ($b=11; $b <= 99; $b++) {
		if (isMultiplePolygon(intval($a.$b))) {
			for ($c=11; $c <= 99; $c++) {
				if (isMultiplePolygon(intval($b.$c))) {
					for ($d=11; $d <= 99; $d++) {
						if (isMultiplePolygon(intval($c.$d))) {
							for ($e=11; $e <= 99; $e++) {
								if (isMultiplePolygon(intval($d.$e))) {
									for ($f=11; $f <= 99; $f++) {
										if (isMultiplePolygon(intval($e.$f))
											&& isMultiplePolygon(intval($f.$a))
											) {
										// if (isOneOfEachPolygon(array($a,$b,$c,$d,$e,$f))
											// ) {
											echo $a," ",$b," ",$c," ",$d," ",$e," ",$f,"\n";
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	// echo "A: ",$a,"\n";
}






$answer = 0;
$endTime = microtime(true);
echo "Answer: ",$answer,"\nTime: ",($endTime - $startTime),"\n";
// Answer: 
// Time: 